name: 'Restart k8s deployment'
description: 'In-cluster deployment restart'

inputs:
  KUSTOMIZE_ROOT:
    description: 'path to kustomize root'
    required: true
  SERVICE:
    description: 'path to kustomize root'
    required: true
  NAMESPACE:
    description: 'path to kustomize root'
    required: true

runs:
  using: "composite"
  steps:
    - name: restart-deployment
      shell: bash
      run: |
        echo "Setting up KUBECTL"
        curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        cd ${{ inputs.KUSTOMIZE_ROOT }}/base
        kubectl rollout restart deployment ${{ inputs.SERVICE }}-${{ env.IMAGE_TAG }} -n ${{ inputs.NAMESPACE }}-pr