name: 'KrakenD conf check'
description: 'Check the KrakenD configuration file'

inputs:
  KRAKEND_CONFIG_FILES_EXPORT:
    description: 'The config file names'
    required: true
  KRAKEND_IMAGE:
    description: 'The KrakenD image'
    required: true

runs:
  using: "composite"
  steps:
    - name: Config Check
      shell: bash {0}
      run: |
      
        KRAKEND_CONFIG_FILE_EXPORT_ARRAY=${{ inputs.KRAKEND_CONFIG_FILES_EXPORT }}
        for i in "${!KRAKEND_CONFIG_FILE_EXPORT_ARRAY[@]}"; do

          result=$(docker run --rm -t -a stdout --name dev-krakend-check --mount type=bind,source="$(pwd)"/${KRAKEND_CONFIG_FILE_EXPORT_ARRAY[i]},target=/etc/krakend/krakend.json,readonly ${{ inputs.KRAKEND_IMAGE }} check -tlc krakend.json -t)

          # Look for the word successful and count the lines that have it
          successful=$(echo $result | grep "Syntax OK!" | wc -l)

          if [ $successful = 0 ]; then
            echo FAILED
            echo "$result"
            exit 1
          else
            echo SUCCESS
          fi
        done
