name: 'Create Git Tag'
description: 'Tag succesfull build'

inputs:
  TAG_NAME:
    description: 'desired tag name'
    required: true
  TAG_MESSAGE:
    description: 'desired tag message'
    required: true

runs:
  using: "composite"
  steps:
    - name: git-tag
      shell: bash
      run: |
        # Create the tag
        git tag -a "${{ inputs.TAG_NAME }}" -m "${{ inputs.TAG_MESSAGE }}"
        git push origin "${{ inputs.TAG_NAME }}" --force