name: 'Create Git Tag'
description: 'Tag succesfull build'

inputs:
  TAG_NAME:
    description: 'desired tag name'
    required: true
  GIT_USER:
    description: 'desired tag name'
    required: true
  GIT_USER_EMAIL:
    description: 'desired tag name'
    required: true

runs:
  using: "composite"
  steps:
    - name: git-tag
      shell: bash
      run: |
        # Create the tag
        git config --global user.email "${{ inputs.GIT_USER_EMAIL }}"
        git config --global user.name "${{ inputs.GIT_USER }}"
        git tag -a "${{ inputs.TAG_NAME }}" -m "${{ inputs.GIT_USER }} triggered build"
        git push origin "${{ inputs.TAG_NAME }}" --force
        