name: 'Deploy using kubectl and kustomize'
description: 'In-cluster deployment'

inputs:
  NAMESPACE:
    description: 'Namespace for the service to be deployed at'
    required: true
  KUSTOMIZE_OVERLAY:
    description: 'path to kustomize overlay'
    required: true

runs:
  using: "composite"
  steps:
    - name: install kubectl, kustomize the deployment, deploy
      shell: bash
      run: |
        echo "Setting up KUBECTL"
        curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        echo "Deploying"
        if [  -z "${{ inputs.NAMESPACE }}" ]; then kubectl apply -k ${{ inputs.KUSTOMIZE_OVERLAY }}; else kubectl apply -n ${{ inputs.NAMESPACE }} -k ${{ inputs.KUSTOMIZE_OVERLAY }}; fi

