name: envsubst
description: This is an action to go thtough all YAML files in repos ./kube/base folder, and change variables

inputs:
  patterns:
    description: Restrict the substitution to a strict set of patterns.
    required: false
  path:
    description: the path to kube base folder
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        FILES=(${{ inputs.path }}/*)
        for FILE in $FILES; do
          if [[ -n ${{ inputs.patterns }} ]] ; then
            envsubst "${{ inputs.patterns }}" < $FILE > /tmp/envsubst || exit 1
          else
            envsubst < $FILE > /tmp/envsubst || exit 1
          fi
          mv /tmp/envsubst $FILE || exit 1
        done
      shell: bash
      env:
        PATH: ${{ inputs.path }}
        PATTERNS: ${{ inputs.patterns }}