name: 'Delete PR using kubectl and kustomize'
description: 'In-cluster PR deletion'

inputs:
  KUSTOMIZE_OVERLAY:
    description: 'path to kustomize overlay'
    required: true

runs:
  using: "composite"
  steps:
    - name: install kubectl, kustomize the deployment, deploy
      shell: bash
      run: |
        echo "Setting up KUBECTL"
        curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        echo "Deleting"
        kubectl delete -k ${{ inputs.KUSTOMIZE_OVERLAY }}
