name: 'KRAKEND configuration check'

on:
  workflow_call:

    inputs:
      SLACK_BUILD_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-build - ID'
      SLACK_BUILD_MESSAGE_ID:
        type: string
        required: true
        description: '#gh-build - Message ID'
      KRAKEND_IMAGE:
        type: string
        required: true
        description: 'KRAKEND Image'
      KRAKEND_CONFIG_FILES_PATH:
        type: string
        required: true
        description: 'KRAKEND Image'
      KRAKEND_CONFIG_FILES_EXPORT:
        type: string
        required: true
        description: 'KRAKEND Image'
    secrets:
      slack-bot-token:
        required: true
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true


jobs:
  workflow:
    runs-on: small-runner
    outputs:
      GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
      
    steps:
      - name: Set environment variables
        id: envs 
        run: |
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
          echo "JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Notify Slack of Check
        id: gh-build
        uses: hitch-technologies/gha-workflows/actions/github-action-slack-notify-build@main
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: |
            Checking KrakenD Config

            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Checkout
        uses: actions/checkout@v1

      - name: Create Config Files
        shell:  bash {0}
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

          KRAKEND_CONFIG_FILE_PATH_ARRAY=${{ inputs.KRAKEND_CONFIG_FILES_PATH }}
          KRAKEND_CONFIG_FILE_EXPORT_ARRAY=${{ inputs.KRAKEND_CONFIG_FILES_EXPORT }}

          for i in "${!KRAKEND_CONFIG_FILE_PATH_ARRAY[@]}"; do
            yq -e '.data."krakend.json"' ${KRAKEND_CONFIG_FILE_PATH_ARRAY[i]} > ${KRAKEND_CONFIG_FILE_EXPORT_ARRAY[i]}
          done

      - name: Running Check
        uses: hitch-technologies/gha-workflows/actions/krakend-check@main
        with:
          KRAKEND_CONFIG_FILES_EXPORT: ${{ inputs.KRAKEND_CONFIG_FILES_EXPORT }}
          KRAKEND_IMAGE: ${{ inputs.KRAKEND_IMAGE }}

      - name: Notify Slack of Success
        if: success()
        uses: hitch-technologies/gha-workflows/actions/github-action-slack-notify-build@main
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: |
            KrakenD Configuration Check Passed

            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Notify Slack of Failure
        if: failure()
        uses: hitch-technologies/gha-workflows/actions/github-action-slack-notify-build@main
        with:
          channel_id: ${{ inputs.SLACK_BUILD_CHANNEL_ID }}
          message_id: ${{ inputs.SLACK_BUILD_MESSAGE_ID }}
          status: |
            KrakenD Configuration Check Failed

            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}
