name: "Deploy PR Networking"

on:
  workflow_call:

    inputs:
      SLACK_PR_MESSAGE_ID:
        type: string
        required: true
        description: 'Initital Message'
      SLACK_PR_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: '#gh-deploy-dev ID'
      PR_KUSTOMIZE_OVERLAY:
        type: string
        required: true
        description: 'Path to Kustomize overlay'
      PR_KUSTOMIZE_ROOT:
        type: string
        required: true
        description: 'Path to Kustomize base'
    secrets:
      slack-bot-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true

jobs:
  workflow:
    runs-on: small-runner
    outputs:
      TAG: ${{ env.TAG }}
      RUN: ${{ env.RUN }}
      GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}

    steps:
      - name: Set environment variables
        id: envs
        run: |
          RUN=pr-${{ github.event.number }}-${{ github.run_number }}
          TAG=pr-${{ github.event.number }}
          echo "TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
          echo "RUN=pr-${{ github.event.number }}-${{ github.run_number }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
          echo "JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Notify Slack of Deploy
        id: gh-deploy-dev
        uses: hitch-technologies/gha-workflows/actions/github-action-slack-notify-build@main
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          status: |
            Deploying PR Network

            - Run: ${{ env.RUN }}
            - PR Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # This step causes issues when used as a composite action
      # Therefore the Script is executed from the step directly
      # This could be the subject of the next upgrade
      - name: Inject image tag into files
        run: |
          find . -type f -name "ingress.yaml" -exec sed 's/$TAG/${{ env.TAG }}/g' {} \;
          find . -type f -name "service.yaml" -exec sed 's/$TAG/${{ env.TAG }}/g' {} \;

        env:
          PATTERN: $TAG 

      - name: Deploy Network
        uses: hitch-technologies/gha-workflows/actions/deploy-pr-network@main
      
      - name: Notify Slack of Success
        if: success()
        uses: hitch-technologies/gha-workflows/actions/github-action-slack-notify-build@main
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.gh-deploy-dev.outputs.message_id }}
          status: |
            PR Network Deployed

            - Run: ${{ env.RUN }}
            - PR Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 

      - name: Notify Slack of Failure
        if: failure()
        uses: hitch-technologies/gha-workflows/actions/github-action-slack-notify-build@main
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.gh-deploy-dev.outputs.message_id }}
          status: |
            PR Network Deployment Failed

            - Run: ${{ env.RUN }}
            - PR Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 