name: "PR Network Setup"

on:
  workflow_call:

    inputs:
      SLACK_PR_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: 'Slack PR deployment channel'
    secrets:
      slack-bot-token:
        required: true
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
        
jobs:
  workflow:
    runs-on: small-runner
    outputs:
      PR_TAG: ${{ env.PR_TAG }}
      IMAGE_TAG: ${{ env.IMAGE_TAG }}
      GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
      
    steps: 

      - name: Slack Start Notification
        id: slack_report_start
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          status: |
            Starting CI/CD Pipeline
          color: 00FFFF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Set environment variables
        id: envs
        run: |
          PR_TAG=pr-${{ github.event.number }}
          echo "PR_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
          echo "JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Inject pr tag into files
        run: |
          find . -type f -name "ingress.yaml" -exec sed -i 's/$PR_TAG/${{ env.PR_TAG }}/g' {} \;
          find . -type f -name "service.yaml" -exec sed -i 's/$PR_TAG/${{ env.PR_TAG }}/g' {} \;
          find . -type f -name "apollo-router.yaml" -exec sed -i 's/$PR_TAG/${{ env.PR_TAG }}/g' {} \;
        env:
          PATTERN: $PR_TAG

      - name: Notify Slack of Deploy
        if: contains(github.head_ref, '_build_') && !contains(fromJson('["closed"]'), github.event.action) && contains(fromJson('["pull_request"]'), github.event_name)
        id: gh-deploy-dev
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.slack_report_start.outputs.message_id }}
          status: |
            Deploying PR Network

            - Run: ${{ env.RUN }}
            - PR Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Deploy Network
        if: contains(github.head_ref, '_build_') && !contains(fromJson('["closed"]'), github.event.action) && contains(fromJson('["pull_request"]'), github.event_name)
        uses: hitch-technologies/gha-workflows/actions/deploy-pr-network@main

      - name: Notify Slack of Success
        if: success() && contains(github.head_ref, '_build_') && !contains(fromJson('["closed"]'), github.event.action) && contains(fromJson('["pull_request"]'), github.event_name)
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.slack_report_start.outputs.message_id }}
          status: |
            PR Network Deployed

            - Pull Request: ${{ github.event.number }}
            - Run: ${{ github.run_number }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 

      - name: Notify Slack of Failure
        if: failure() && contains(github.head_ref, '_build_') && !contains(fromJson('["closed"]'), github.event.action) && contains(fromJson('["pull_request"]'), github.event_name)
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.slack_report_start.outputs.message_id }}
          status: |
            PR Network Deployment Failed

            - Pull Request: ${{ github.event.number }}
            - Run: ${{ github.run_number }}
            - Job URL: ${{ env.JOB_URL }}
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Notify Slack of Cleanup
        if: contains(github.head_ref, '_build_') && contains(fromJson('["closed"]'), github.event.action) && contains(fromJson('["pull_request"]'), github.event_name)
        id: gh-deploy-cleanup
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.slack_report_start.outputs.message_id }}
          status: |
            Cleaning PR Network

            - Pull Request: ${{ github.event.number }}
            - Run: ${{ github.run_number }}
            - Job URL: ${{ env.JOB_URL }}
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Delete Network
        if: contains(github.head_ref, '_build_') && contains(fromJson('["closed"]'), github.event.action) && contains(fromJson('["pull_request"]'), github.event_name)
        uses: hitch-technologies/gha-workflows/actions/delete-pr-network@main
      
      - name: Notify Slack of Cleanup Success
        if: success() && contains(github.head_ref, '_build_') && contains(fromJson('["closed"]'), github.event.action) && contains(fromJson('["pull_request"]'), github.event_name)
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.slack_report_start.outputs.message_id }}
          status: |
            PR Network Deleted

            - Pull Request: ${{ github.event.number }}
            - Run: ${{ github.run_number }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 

      - name: Notify Slack of Cleanup Failure
        if: failure() && contains(github.head_ref, '_build_') && contains(fromJson('["closed"]'), github.event.action) && contains(fromJson('["pull_request"]'), github.event_name)
        uses: FlexCharge/github-action-slack-notify-build@f953c3ec8cd2f6f726a9a87bf87ac30cab0a1e19
        with:
          channel_id: ${{ inputs.SLACK_PR_DEPLOY_CHANNEL_ID }}
          message_id: ${{ steps.slack_report_start.outputs.message_id }}
          status: |
            PR Network Cleanup Failed

            - Pull Request: ${{ github.event.number }}
            - Run: ${{ github.run_number }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }} 