name: "Run Prisma Migration"

on:
  workflow_call:

    inputs:
      SLACK_DEPLOY_CHANNEL_ID:
        type: string
        required: true
        description: '#gha-builds - ID'
      ECR_FULL_PATH:
        type: string
        required: true
        description: 'Elastic Container Repository of the service'
      GITHUB_RUNNER:
        type: string
        required: true
        description: 'Name of GitHub Runner'
    secrets:
      slack-bot-token:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true
      postgres-database-url:
        required: true

jobs:
  workflow:
    runs-on: ${{ inputs.GITHUB_RUNNER }}

    steps:
      - name: Set environment variables
        run: |
          echo "SHORT_COMMIT=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF##*/}-`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
          echo "JOB_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Notify Slack of Deployment
        id: gh-deploy-prod
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          channel: ${{ inputs.SLACK_DEPLOY_CHANNEL }}
          status: |
            Starting Prisma Migration

            - Image Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: 0037FF
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v4

      - name: Pull migration image
        run: |
          docker pull ${{ inputs.ECR_FULL_PATH }}:${{ env.TAG }}

      - name: Run migration image
        run: |
          docker run -e POSTGRES_DATABASE_URL=${{ secrets.postgres-database-url }} ${{ inputs.ECR_FULL_PATH }}:${{ env.TAG }}

      - name: Notify Slack of Success
        if: success()
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          channel: ${{ inputs.SLACK_DEPLOY_CHANNEL }}
          message_id: ${{ steps.gh-deploy-prod.outputs.message_id }}
          status: |
            Prisma Migration Completed

            - Image Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

      - name: Notify Slack of Failure
        if: failure()
        uses: zuplo/github-action-slack-notify-build@v2
        with:
          channel: ${{ inputs.SLACK_DEPLOY_CHANNEL }}
          message_id: ${{ steps.gh-deploy-prod.outputs.message_id }}
          status: |
            Prisma Migration Failed

            - Image Tag: ${{ env.TAG }}
            - Actor: ${{ env.GITHUB_ACTOR }}
            - Job URL: ${{ env.JOB_URL }}
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack-bot-token }}

